name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
      - name: Check can publish
        id: can_publish
        run: npx can-npm-publish --verbose
      - name: Install modules
        run: yarn install
      - name: Run unit test
        run: yarn run test
      - name: Build
        run: yarn run build
      - name: Publish npm module
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: No Update
        if: failure() && steps.can_publish.outcome == 'failure'
        run: echo "No Update"
